### PR TITLE
fixed(privacy and terms):remove back button

### PR DESCRIPTION
**Pull request by iPR0D1G1**
Fixed:  #6018

### CODE REVIEW

**Comment by RemcoSimonides** [comment]
In what case do we still need to see this button? I think we don't need this button anymore

**Comment by pldespaigne** [comment]
We need it in case it's open in the app (not as a new tab)
https://github.com/blockframes/blockframes/issues/6018

**Review by pldespaigne — CHANGES_REQUESTED** [review]
Perfect ! but prefer `camelCase` over `snake_case` for the `no_back` variable.
Also this need to be in the release, so you should change your target branch from `develop` to `fix-for-release-3-2-1`

**Comment by pldespaigne** [comment]
Closed, because #6018 was mistakenly reopen but there was no real issue

**Pull request closed without merging**
