### PR TITLE
Fix overflow issue on firefox

### PR DESCRIPTION
**Pull request by RemcoSimonides**
Fix issue #4549

### CODE REVIEW

**Comment by RemcoSimonides** [comment]
Merge after release to avoid side effects in current release

**Comment by phpgeekfr** [comment]
minmax is not IE compatible 
image
https://developer.mozilla.org/en-US/docs/Web/CSS/minmax()
Is this an issue ?

**Comment by GrandSchtroumpf** [comment]
no

**Review by GrandSchtroumpf — APPROVED** [review]
Please test intensively on different browsers with different movies (short text, long text, poster, no poster).

**Comment by RemcoSimonides** [comment]
Closed in favor of #4581

**Pull request closed without merging**
